name: node.js
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - run: sudo timedatectl set-timezone America/New_York
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm run predeploy
      - run: aws s3 cp lambda.zip s3://covid-vaccine-scraper-test/lambda.zip
      - run: aws lambda update-function-code --function-name scrapeCovidAppointmentDataTEST \
                   --s3-bucket covid-vaccine-scraper-test --s3-key lambda.zip --publish
      - run: npx prettier --check ./
